[package]
name = "impl-more"
version = "0.0.4"
description = "Concise trait implementations"
authors = ["Rob Ede <robjtede@icloud.com>"]
keywords = ["no-std"]
categories = ["no-std"]
license = "MIT OR Apache-2.0"
edition = "2018"
rust-version = "1.56"

[dependencies]

[dev-dependencies]
static_assertions = "1.1"
